[project]
name = "spidercreator"
version = "0.1.0"
description = "Automated web scraping spider generation using Browser Use and LLMs. Streamline the creation of Playwright-based spiders with minimal manual coding. Ideal for large enterprises with recurring data extraction needs."
readme = "README.md"
requires-python = ">=3.11,<3.13" 
dependencies = [
    "pydantic>=2.11.7",
    "attrs>=25.3.0",
    "attrs-strict>=1.0.1",
    "betterhtmlchunking>=0.9.2",
    "fastapi>=0.116.1",
    "pandas>=2.3.2",
    "prettyprinter>=0.18.0",
    "ptyprocess>=0.7.0",
    "pyhtml2md>=1.7.0",
    "pyobjtojson>=0.3",
    "sounddevice>=0.5.2",
    "tldextract>=5.3.0",
    "uvicorn>=0.35.0",
    "validators>=0.35.0",
    "browser-use>=0.6.1",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]
